//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JustLauncher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Nav_Play { get { return ResourceManager.GetString("Nav_Play", resourceCulture); } }
        public static string Nav_Accounts { get { return ResourceManager.GetString("Nav_Accounts", resourceCulture); } }
        public static string Nav_Settings { get { return ResourceManager.GetString("Nav_Settings", resourceCulture); } }
        public static string Nav_Console { get { return ResourceManager.GetString("Nav_Console", resourceCulture); } }
        public static string Nav_About { get { return ResourceManager.GetString("Nav_About", resourceCulture); } }
        
        public static string Common_Close { get { return ResourceManager.GetString("Common_Close", resourceCulture); } }
        public static string Common_Cancel { get { return ResourceManager.GetString("Common_Cancel", resourceCulture); } }
        public static string Common_Save { get { return ResourceManager.GetString("Common_Save", resourceCulture); } }
        public static string Common_Delete { get { return ResourceManager.GetString("Common_Delete", resourceCulture); } }
        public static string Common_Edit { get { return ResourceManager.GetString("Common_Edit", resourceCulture); } }
        public static string Common_Add { get { return ResourceManager.GetString("Common_Add", resourceCulture); } }
        public static string Common_Browse { get { return ResourceManager.GetString("Common_Browse", resourceCulture); } }
        
        public static string Home_SetupTitle { get { return ResourceManager.GetString("Home_SetupTitle", resourceCulture); } }
        public static string Home_SetupDescription { get { return ResourceManager.GetString("Home_SetupDescription", resourceCulture); } }
        public static string Home_OfflineTitle { get { return ResourceManager.GetString("Home_OfflineTitle", resourceCulture); } }
        public static string Home_OfflineDescription { get { return ResourceManager.GetString("Home_OfflineDescription", resourceCulture); } }
        public static string Home_ElyByTitle { get { return ResourceManager.GetString("Home_ElyByTitle", resourceCulture); } }
        public static string Home_ElyByDescription { get { return ResourceManager.GetString("Home_ElyByDescription", resourceCulture); } }
        public static string Home_Continue { get { return ResourceManager.GetString("Home_Continue", resourceCulture); } }
        
        public static string Play_LaunchButton { get { return ResourceManager.GetString("Play_LaunchButton", resourceCulture); } }
        public static string Play_AddInstallation { get { return ResourceManager.GetString("Play_AddInstallation", resourceCulture); } }
        public static string Play_StatusReady { get { return ResourceManager.GetString("Play_StatusReady", resourceCulture); } }
        public static string Play_StatusLaunching { get { return ResourceManager.GetString("Play_StatusLaunching", resourceCulture); } }
        public static string Play_StatusDownloading { get { return ResourceManager.GetString("Play_StatusDownloading", resourceCulture); } }
        public static string Play_NoInstallations { get { return ResourceManager.GetString("Play_NoInstallations", resourceCulture); } }
        
        public static string Accounts_Title { get { return ResourceManager.GetString("Accounts_Title", resourceCulture); } }
        public static string Accounts_Description { get { return ResourceManager.GetString("Accounts_Description", resourceCulture); } }
        public static string Accounts_AddAccount { get { return ResourceManager.GetString("Accounts_AddAccount", resourceCulture); } }
        public static string Accounts_NoAccounts { get { return ResourceManager.GetString("Accounts_NoAccounts", resourceCulture); } }
        public static string Accounts_AccountName { get { return ResourceManager.GetString("Accounts_AccountName", resourceCulture); } }
        public static string Accounts_AccountType { get { return ResourceManager.GetString("Accounts_AccountType", resourceCulture); } }
        
        public static string Settings_Title { get { return ResourceManager.GetString("Settings_Title", resourceCulture); } }
        public static string Settings_General { get { return ResourceManager.GetString("Settings_General", resourceCulture); } }
        public static string Settings_Language { get { return ResourceManager.GetString("Settings_Language", resourceCulture); } }
        public static string Settings_LanguageDescription { get { return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture); } }
        public static string Settings_MinecraftDirectory { get { return ResourceManager.GetString("Settings_MinecraftDirectory", resourceCulture); } }
        public static string Settings_JavaPath { get { return ResourceManager.GetString("Settings_JavaPath", resourceCulture); } }
        public static string Settings_JavaPathDescription { get { return ResourceManager.GetString("Settings_JavaPathDescription", resourceCulture); } }
        public static string Settings_Memory { get { return ResourceManager.GetString("Settings_Memory", resourceCulture); } }
        public static string Settings_MinMemory { get { return ResourceManager.GetString("Settings_MinMemory", resourceCulture); } }
        public static string Settings_MaxMemory { get { return ResourceManager.GetString("Settings_MaxMemory", resourceCulture); } }
        public static string Settings_GameSettings { get { return ResourceManager.GetString("Settings_GameSettings", resourceCulture); } }
        public static string Settings_WindowWidth { get { return ResourceManager.GetString("Settings_WindowWidth", resourceCulture); } }
        public static string Settings_WindowHeight { get { return ResourceManager.GetString("Settings_WindowHeight", resourceCulture); } }
        public static string Settings_Fullscreen { get { return ResourceManager.GetString("Settings_Fullscreen", resourceCulture); } }
        public static string Settings_JvmArguments { get { return ResourceManager.GetString("Settings_JvmArguments", resourceCulture); } }
        public static string Settings_JvmArgumentsDescription { get { return ResourceManager.GetString("Settings_JvmArgumentsDescription", resourceCulture); } }
        
        public static string Console_Title { get { return ResourceManager.GetString("Console_Title", resourceCulture); } }
        public static string Console_CopyLog { get { return ResourceManager.GetString("Console_CopyLog", resourceCulture); } }
        public static string Console_ClearLog { get { return ResourceManager.GetString("Console_ClearLog", resourceCulture); } }
        
        public static string About_Title { get { return ResourceManager.GetString("About_Title", resourceCulture); } }
        public static string About_Description { get { return ResourceManager.GetString("About_Description", resourceCulture); } }
        public static string About_CreatedBy { get { return ResourceManager.GetString("About_CreatedBy", resourceCulture); } }
        public static string About_GitHub { get { return ResourceManager.GetString("About_GitHub", resourceCulture); } }
        public static string About_Website { get { return ResourceManager.GetString("About_Website", resourceCulture); } }
        
        public static string AccountDialog_AddAccount { get { return ResourceManager.GetString("AccountDialog_AddAccount", resourceCulture); } }
        public static string AccountDialog_OfflineMode { get { return ResourceManager.GetString("AccountDialog_OfflineMode", resourceCulture); } }
        public static string AccountDialog_ElyByAccount { get { return ResourceManager.GetString("AccountDialog_ElyByAccount", resourceCulture); } }
        public static string AccountDialog_Username { get { return ResourceManager.GetString("AccountDialog_Username", resourceCulture); } }
        public static string AccountDialog_Email { get { return ResourceManager.GetString("AccountDialog_Email", resourceCulture); } }
        public static string AccountDialog_Password { get { return ResourceManager.GetString("AccountDialog_Password", resourceCulture); } }
        public static string AccountDialog_Login { get { return ResourceManager.GetString("AccountDialog_Login", resourceCulture); } }
        
        public static string InstallationDialog_Title { get { return ResourceManager.GetString("InstallationDialog_Title", resourceCulture); } }
        public static string InstallationDialog_Name { get { return ResourceManager.GetString("InstallationDialog_Name", resourceCulture); } }
        public static string InstallationDialog_Version { get { return ResourceManager.GetString("InstallationDialog_Version", resourceCulture); } }
        public static string InstallationDialog_SelectVersion { get { return ResourceManager.GetString("InstallationDialog_SelectVersion", resourceCulture); } }
        public static string InstallationDialog_Create { get { return ResourceManager.GetString("InstallationDialog_Create", resourceCulture); } }
        
        public static string Message_ErrorTitle { get { return ResourceManager.GetString("Message_ErrorTitle", resourceCulture); } }
        public static string Message_SuccessTitle { get { return ResourceManager.GetString("Message_SuccessTitle", resourceCulture); } }
        public static string Message_WarningTitle { get { return ResourceManager.GetString("Message_WarningTitle", resourceCulture); } }
        public static string Message_LaunchError { get { return ResourceManager.GetString("Message_LaunchError", resourceCulture); } }
        public static string Message_LoginError { get { return ResourceManager.GetString("Message_LoginError", resourceCulture); } }
        public static string Message_JavaNotFound { get { return ResourceManager.GetString("Message_JavaNotFound", resourceCulture); } }
        public static string Message_InvalidJavaVersion { get { return ResourceManager.GetString("Message_InvalidJavaVersion", resourceCulture); } }
    }
}
